language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - "node_modules"
script:
  - yarn test
  - yarn build
deploy:
  - provider: script
    script: cp package.json build/ && cd build && now --public --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true
