language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - "node_modules"
script:
  - yarn test
  - yarn build
before_deploy: npm install now --no-save
deploy:
  - provider: script
    script: now build --token $NOW_TOKEN
    skip_cleanup: true
    on:
      all_branches: true
      master: false
  - provider: script
    script: now --token $NOW_TOKEN && now alias --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true
