language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - "node_modules"
script:
  - yarn test
  - yarn build
deploy:
  - provider: script
    script: yarn now build --public --alias pb-demo --token $NOW_TOKEN 
    skip_cleanup: true
    on:
      master: true
