language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - "node_modules"
script:
  - yarn test
  - yarn build
deploy:
  - provider: script
    script: mv build pb-demo && now alias --token=$NOW_TOKEN $(now pb-demo --static --no-clipboard --token=$NOW_TOKEN --public) pb-demo
    skip_cleanup: true
    on:
      master: true
